#!/usr/bin/env bash
#print Best School 10 times but add Hi on new line after the 9th iteration.
i=1
while [ $i -lt 11 ]
do
   echo "Best School"
   ((i++))
   if [ $i -eq 9 ]; then
	   printf "Best School\n Hi"
   fi
done

