#!/usr/bin/env bash
#Print best school 10 times but display bad luck good luck on 4 & 8 respectively
i=1
while [ $i -le 10 ]
do
       if [ $i -eq 4 ]; then
            echo "bad luck"
       elif [ $i -eq 8 ]; then
            echo "good luck"
       else
           echo "Best School"
       fi
       ((i++))
done
