#!/usr/bin/env bash
#Display time for 12h 59 min.
hour=0
minutes=0
while [ $hour -le 12 ]
do 
   echo "Hour:$hour"
   while [ $minutes -lt 60 ]
   do
   echo "$minutes"
   ((minutes++))
   done
   ((hour++))
   minutes=0
done 
