#!/usr/bin/env bash
#manages the manage_process file using init.d 
case "$1" in
	start)
		./manage_my_process &
		touch /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
	        pkill -x manage_my_process
	        rm -f /var/run/my_process.pid
	        echo "manage_my_process stopped"
		;;
	restart)
	        pkill -x manage_my_process
		rm -f /var/run/my_process.pid
		./manage_my_process &
		touch /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	*)
	        echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
		;;
	esac

